#!/bin/sh
# Copyright (c) 2008-2022 Apple Inc.
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation files
# (the "Software"), to deal in the Software without restriction,
# including without limitation the rights to use, copy, modify, merge,
# publish, distribute, sublicense, and/or sell copies of the Software,
# and to permit persons to whom the Software is furnished to do so,
# subject to the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT.  IN NO EVENT SHALL THE ABOVE LISTED COPYRIGHT
# HOLDER(S) BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name(s) of the above
# copyright holders shall not be used in advertising or otherwise to
# promote the sale, use or other dealings in this Software without
# prior written authorization.

[[ -e /etc/sshd_config ]] && SSHD_CONFIG=/etc/sshd_config
[[ -e /etc/ssh/sshd_config ]] && SSHD_CONFIG=/etc/ssh/sshd_config

[[ -e /etc/ssh_config ]] && SSH_CONFIG=/etc/ssh_config
[[ -e /etc/ssh/ssh_config ]] && SSH_CONFIG=/etc/ssh/ssh_config

if [[ -n "${SSHD_CONFIG}" ]] ; then
    if ! cat ${SSHD_CONFIG} | grep -v '^#' | egrep -q '^(Match|XAuthLocation)' ; then
    {
        echo ""
        echo "# XAuthLocation added by XQuartz (https://www.xquartz.org)"
        echo "XAuthLocation /opt/X11/bin/xauth"
    } >> ${SSHD_CONFIG}
    fi
fi

if [[ -n "${SSH_CONFIG}" ]] ; then
    if ! cat ${SSH_CONFIG} | grep -v '^#' | grep -q 'XAuthLocation' ; then
    {
        echo ""
        echo "# XAuthLocation added by XQuartz (https://www.xquartz.org)"
        echo "Host *"
        echo "    XAuthLocation /opt/X11/bin/xauth"
    } >> ${SSH_CONFIG}
    fi
fi
